[auth]
allowed_redirect_urls = [
  "https://limraresturent.in",
  "https://limraresturent.in/admin.html",
  "https://limraresturent.in/admin-login.html",
  "https://www.limraresturent.in",
  "https://www.limraresturent.in/admin.html",
  "https://www.limraresturent.in/admin-login.html",
  "https://vb9ucr22.insforge.site",
  "https://vb9ucr22.insforge.site/admin.html",
  "https://vb9ucr22.insforge.site/admin-login.html",
  "http://localhost:5173",
  "http://localhost:5173/admin.html",
  "http://localhost:5173/admin-login.html",
]
require_email_verification = true
verify_email_method = "code"
reset_password_method = "code"

[auth.password]
min_length = 6
require_number = false
require_lowercase = false
require_uppercase = false
require_special_char = false

[auth.smtp]
enabled = false
host = ""
port = 465
username = ""
sender_email = ""
sender_name = ""
min_interval_seconds = 60
